fo = open("file.txt", "r+")
str1 = fo.read(3)
str2 = fo.read(2)
str3 = fo.readline()
str4 = fo.readline()
print(str1)
print(str2)
print(str3)
print(str4)
fo.close()

fo = open('file.txt', "r+")
fo.write("Hello world \n")
fo.write("Hello sky \n")
fo.close()
